# Generated by Django 4.0 on 2022-02-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_spyder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='original_comments',
            name='commentID',
            field=models.CharField(max_length=100, unique=True, verbose_name='评论ID'),
        ),
    ]
