# Generated by Django 4.0 on 2022-02-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_spyder', '0002_alter_original_comments_commentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='original_comments',
            name='comment_content',
            field=models.TextField(max_length=1000, verbose_name='评论内容'),
        ),
    ]
