# Generated by Django 3.2.5 on 2022-04-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_spyder', '0003_alter_original_comments_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='hash',
            field=models.CharField(default=1, max_length=100, unique=True, verbose_name='图片标识'),
            preserve_default=False,
        ),
    ]
