# Generated by Django 3.2.5 on 2022-04-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_spyder', '0004_picture_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='original_comments',
            name='tokScore',
            field=models.CharField(default=1, max_length=30, verbose_name='分类'),
            preserve_default=False,
        ),
    ]
