# Generated by Django 3.2.5 on 2022-04-03 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_spyder', '0005_original_comments_tokscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='original_product',
            name='spyder_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 3, 13, 6, 40, 207414), verbose_name='爬取日期'),
        ),
    ]
